USE sakila;

-- List the number of films per category.

SELECT ca.name, COUNT(fc.film_id) AS 'number_films'
FROM sakila.film_category AS fc
LEFT JOIN sakila.category AS ca
ON ca.category_id = fc.category_id
GROUP BY ca.category_id, ca.name;

-- Retrieve the store ID, city, and country for each store.

SELECT s.store_id, ci.city, co.country
FROM sakila.store AS s
JOIN sakila.address AS a ON s.address_id = a.address_id
JOIN sakila.city AS ci ON a.city_id = ci.city_id
JOIN sakila.country AS co ON ci.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, SUM(p.amount) AS 'Total_Revenue'
FROM sakila.payment AS p
JOIN sakila.rental AS r ON p.rental_id = r.rental_id
JOIN sakila.inventory AS i ON r.inventory_id = i.inventory_id
JOIN sakila.store AS s ON i.store_id = s.store_id
GROUP BY s.store_id;

-- Determine the average running time of films for each category.

SELECT c.name AS category_name, AVG(f.length) AS avg_running_time
FROM sakila.film_category AS fc
JOIN sakila.film AS f ON fc.film_id = f.film_id
JOIN sakila.category AS c ON fc.category_id = c.category_id
GROUP BY c.name;
